# Site settings
title: Atef Arfaoui 
description: 'Software / Data Engineer - 5+ years Python/API developer; Django, Flask, FastAPI...  Pipeline engineering with Airflow/Luigi/AWS...'
url: 'https://atef.site'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'atef-site'

author:
  name: 'Atef Arfaoui'
  email: arfatef@gmail.com
  twitter_username: ArfaouiAtef
  # resume: Atef_Arfaoui__CV.pdf
  # facebook_username: joshgerdes
  github_username:  arfaoui47
  linkedin_username:  atefarfaoui

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:month/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']

layout: default
comments: true